name: 'Create rendered template PR'
description: |
  This action creates a PR in the rendered template repository.
  It creates a PR for the updates applied by the `update-rendered-template` action.

author: EIDP
branding:
  color: 'green'
  icon: 'git-pull-request'

inputs:
  github-token:
    description: 'GitHub token for authentication. It must have permissions to read and write to the rendered repository. A GitHub App token is recommended.'
    required: true
  rendered-repo-path:
    description: 'Path where the rendered repository is cloned to.'
    required: false
    default: 'rendered-repo'

outputs:
  pull-request-number:
    description: 'The number of the created pull request.'
    value: ${{ steps.create-pr.outputs.pull-request-number }}
  branch-name:
    description: 'The name of the branch for the created pull request.'
    value: ${{ steps.create-pr.outputs.branch-name }}

runs:
  using: 'composite'
  steps:
  - name: Create Pull Request
    id: create-pr
    uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
    with:
      token: ${{ inputs.github-token }}
      path: ${{ inputs.rendered-repo-path }}
      branch: template-update/${{ github.event.pull_request.number }}
      commit-message: |
        Update from template PR #${{ github.event.pull_request.number }}

        Auto-generated by cruft update
      title: "[Template Update] ${{ github.event.pull_request.title }}"
      body: |
        This PR applies changes from template PR #${{ github.event.pull_request.number }}:
        ${{ github.event.pull_request.html_url }}

        ## Changes
        Generated by `cruft update` from ${{ github.repository }}.

        The template branch `${{ github.head_ref }}` was used to generate these changes.
      draft: false
